---
- name: 'Add the Google Stackdriver monitoring yum repository.'
  yum_repository:
    name: google-cloud-monitoring
    baseurl: '{{ stackdriver_monitoring_repo }}-{{ stackdriver_monitoring_repo_suffix }}'
    description: A google repo that contains monitoring stuff
    gpgkey: '{{ gpgkeys }}'
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes

- name: 'Add the Google Stackdriver logging yum repository.'
  yum_repository:
    name: google-cloud-logging
    baseurl: '{{ stackdriver_logging_repo }}-{{ stackdriver_logging_repo_suffix }}'
    description: A google repo that contains logging stuff
    gpgkey: '{{ gpgkeys }}'
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes

- name: 'Yum installing stackdriver-agent'
  yum:
    name: 'stackdriver-agent'
    state: present

- name: 'Yum installing google-fluentd'
  yum:
    name: 'google-fluentd'
    state: present

- name: 'Yum installing google-fluentd-catch-all-config'
  yum:
    name: 'google-fluentd-catch-all-config'
    state: present

- name: 'adding stackdriver configs'
  template:
    src: stackdriver.sysconfig
    dest: '{{ stackdriver_sysconfig }}'
    backup: yes
  notify:
    - restart stackdriver-agent

- name: 'Custom configs'
  template:
    src: '{{ sd_item.template }}.conf.j2'
    dest: '/etc/google-fluentd/config.d/{{ sd_item.name }}.conf'
    owner: root
    mode: 0640
  with_items: '{{ stackdriver_custom_configs }}'
  loop_control:
    loop_var: sd_item
  when: stackdriver_custom_configs|length > 0
  notify:
    - restart google-fluentd

- name: "Custom openvpnas config"
  template:
    src: "openvpnas.conf.j2"
    dest: "/etc/google-fluentd/config.d/openvpnas.conf.j2"
    owner: root
    mode: 0640
  when: stackdriver_openvas

#did below like this cause loop didnt work will fix later
- name: 'Starting service stackdriver-agent'
  systemd:
    state: started
    name: stackdriver-agent
    enabled: yes

- name: 'Starting service google-fluentd'
  systemd:
    state: started
    name: google-fluentd
    enabled: yes

- name: Restart cron job exists
  cron:
    name: 'restart stackdriver'
    minute: 0
    job: 'service google-fluentd restart'
    user: 'root'
  when: stackdriver_restart
